/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app': RouteRecordInfo<
      '/app',
      '/app',
      Record<never, never>,
      Record<never, never>,
      | '/app/'
      | '/app/[...catchAll]'
      | '/app/companies/'
      | '/app/companies/[...catchAll]'
      | '/app/companies/[id]'
      | '/app/masterProducts/'
      | '/app/orders/'
      | '/app/price-check/'
      | '/app/settings/billing'
      | '/app/suppliers/'
      | '/app/suppliers/[id]'
      | '/app/users/'
    >,
    '/app/': RouteRecordInfo<
      '/app/',
      '/app',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/[...catchAll]': RouteRecordInfo<
      '/app/[...catchAll]',
      '/app/:catchAll(.*)',
      { catchAll: ParamValue<true> },
      { catchAll: ParamValue<false> },
      | never
    >,
    '/app/companies/': RouteRecordInfo<
      '/app/companies/',
      '/app/companies',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/companies/[...catchAll]': RouteRecordInfo<
      '/app/companies/[...catchAll]',
      '/app/companies/:catchAll(.*)',
      { catchAll: ParamValue<true> },
      { catchAll: ParamValue<false> },
      | never
    >,
    '/app/companies/[id]': RouteRecordInfo<
      '/app/companies/[id]',
      '/app/companies/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/app/masterProducts/': RouteRecordInfo<
      '/app/masterProducts/',
      '/app/masterProducts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/orders/': RouteRecordInfo<
      '/app/orders/',
      '/app/orders',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/price-check/': RouteRecordInfo<
      '/app/price-check/',
      '/app/price-check',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/settings/billing': RouteRecordInfo<
      '/app/settings/billing',
      '/app/settings/billing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/suppliers/': RouteRecordInfo<
      '/app/suppliers/',
      '/app/suppliers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/suppliers/[id]': RouteRecordInfo<
      '/app/suppliers/[id]',
      '/app/suppliers/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/app/users/': RouteRecordInfo<
      '/app/users/',
      '/app/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/callback': RouteRecordInfo<
      '/auth/callback',
      '/auth/callback',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/forgot-password': RouteRecordInfo<
      '/auth/forgot-password',
      '/auth/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/login': RouteRecordInfo<
      '/auth/login',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/reset-password': RouteRecordInfo<
      '/auth/reset-password',
      '/auth/reset-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/app.vue': {
      routes:
        | '/app'
        | '/app/'
        | '/app/[...catchAll]'
        | '/app/companies/'
        | '/app/companies/[...catchAll]'
        | '/app/companies/[id]'
        | '/app/masterProducts/'
        | '/app/orders/'
        | '/app/price-check/'
        | '/app/settings/billing'
        | '/app/suppliers/'
        | '/app/suppliers/[id]'
        | '/app/users/'
      views:
        | 'default'
    }
    'src/pages/app/index.vue': {
      routes:
        | '/app/'
      views:
        | never
    }
    'src/pages/app/[...catchAll].vue': {
      routes:
        | '/app/[...catchAll]'
      views:
        | never
    }
    'src/pages/app/companies/index.vue': {
      routes:
        | '/app/companies/'
      views:
        | never
    }
    'src/pages/app/companies/[...catchAll].vue': {
      routes:
        | '/app/companies/[...catchAll]'
      views:
        | never
    }
    'src/pages/app/companies/[id].vue': {
      routes:
        | '/app/companies/[id]'
      views:
        | never
    }
    'src/pages/app/masterProducts/index.vue': {
      routes:
        | '/app/masterProducts/'
      views:
        | never
    }
    'src/pages/app/orders/index.vue': {
      routes:
        | '/app/orders/'
      views:
        | never
    }
    'src/pages/app/price-check/index.vue': {
      routes:
        | '/app/price-check/'
      views:
        | never
    }
    'src/pages/app/settings/billing.vue': {
      routes:
        | '/app/settings/billing'
      views:
        | never
    }
    'src/pages/app/suppliers/index.vue': {
      routes:
        | '/app/suppliers/'
      views:
        | never
    }
    'src/pages/app/suppliers/[id].vue': {
      routes:
        | '/app/suppliers/[id]'
      views:
        | never
    }
    'src/pages/app/users/index.vue': {
      routes:
        | '/app/users/'
      views:
        | never
    }
    'src/pages/auth/callback.vue': {
      routes:
        | '/auth/callback'
      views:
        | never
    }
    'src/pages/auth/forgot-password.vue': {
      routes:
        | '/auth/forgot-password'
      views:
        | never
    }
    'src/pages/auth/login.vue': {
      routes:
        | '/auth/login'
      views:
        | never
    }
    'src/pages/auth/reset-password.vue': {
      routes:
        | '/auth/reset-password'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
